In [1]:
pip install tensorflow

In [2]:
import tensorflow as tf
print(tf.__version__)

2.19.0


In [3]:
a=tf.constant(5)
print(a)

v=tf.constant([1,2,3,4])
print(v)

m = tf.constant([[1,2], [3,4]])
print(m)

t3=tf.constant([[[1,2],
                [3,4]],
                [[5,6],
                [7,8]]])
print(t3)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [4]:
a = tf.constant([10, 20, 30])
b = tf.constant([50, 60, 70])
print(a+b)

tf.Tensor([ 60  80 100], shape=(3,), dtype=int32)


In [10]:
a = tf.constant(6.0)
b = tf.constant(3.0)


add = tf.add(a, b)
sub = tf.subtract(a, b)
mul = tf.multiply(a, b)
div = tf.divide(a, b)
pow_ = tf.pow(a, b)

print("Add:", add.numpy())
print("Sub:", sub.numpy())
print("Mul:", mul.numpy())
print("Div:", div.numpy())
print("Pow:", pow_.numpy())

Add: 9.0
Sub: 3.0
Mul: 18.0
Div: 2.0
Pow: 216.0


In [9]:
import tensorflow as tf


a = tf.constant([1.0, 2.0, 3.0])
b = tf.constant([4.0, 5.0, 6.0])


add = tf.add(a, b)
sub = tf.subtract(a, b)
mul = tf.multiply(a, b)
div = tf.divide(a, b)
pow_ = tf.pow(a, b)

print("Add:", add.numpy())
print("Sub:", sub.numpy())
print("Mul:", mul.numpy())
print("Div:", div.numpy())
print("Pow:", pow_.numpy())


Add: [5. 7. 9.]
Sub: [-3. -3. -3.]
Mul: [ 4. 10. 18.]
Div: [0.25 0.4  0.5 ]
Pow: [  1.  32. 729.]


In [11]:
import tensorflow as tf

# Define 2D matrices
A = tf.constant([[1.0, 2.0],
                 [3.0, 4.0]])

B = tf.constant([[5.0, 6.0],
                 [7.0, 8.0]])

# Element-wise operations
add = tf.add(A, B)
sub = tf.subtract(A, B)
mul = tf.multiply(A, B)
div = tf.divide(A, B)
pow_ = tf.pow(A, B)

print("Add:\n", add.numpy())
print("Sub:\n", sub.numpy())
print("Mul:\n", mul.numpy())
print("Div:\n", div.numpy())
print("Pow:\n", pow_.numpy())


Add:
 [[ 6.  8.]
 [10. 12.]]
Sub:
 [[-4. -4.]
 [-4. -4.]]
Mul:
 [[ 5. 12.]
 [21. 32.]]
Div:
 [[0.2        0.33333334]
 [0.42857143 0.5       ]]
Pow:
 [[1.0000e+00 6.4000e+01]
 [2.1870e+03 6.5536e+04]]


In [6]:
a = tf.constant([10, 20, 30])
print(a.dtype, a.shape, tf.rank(a))

<dtype: 'int32'> (3,) tf.Tensor(1, shape=(), dtype=int32)


In [8]:
import numpy as np
np_array = ([[1,2,3], [4,5,6]])

tensor = tf.convert_to_tensor(np_array)
print(tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
